name: docker build
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate tags
        id: tags
        uses: greboid/docker-tags-action@v5.0.2
        with:
          separator: ' '
          fullname: 'false' 

      - name: Build news image
        id: build-news-image
        uses: redhat-actions/buildah-build@v2.6.2
        with:
          dockerfiles: news.Dockerfile
          image: ${{ github.repository }}/news
          tags: ${{ steps.tags.outputs.tags }}
          extra-args: >
            --timestamp
            0

      - name: Push news to GHCR
        uses: redhat-actions/push-to-registry@v2.3.2
        with:
          image: ${{ steps.build-news-image.outputs.image }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.tags.outputs.tags }}


      - name: Build arch image
        id: build-arch-image
        uses: redhat-actions/buildah-build@v2.6.2
        with:
          dockerfiles: arch.Dockerfile
          image: ${{ github.repository }}/arch
          tags: ${{ steps.tags.outputs.tags }}
          extra-args: >
            --timestamp
            0

      - name: Push arch to GHCR
        uses: redhat-actions/push-to-registry@v2.3.2
        with:
          image: ${{ steps.build-arch-image.outputs.image }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.tags.outputs.tags }}
